export enum EntityType{
    CondoUnit = 0,
    Contact = 1,
    Contract = 2,
    ForSale = 3,
    Land = 4,
    Company = 5,
    Property = 6,
    SpaceForLease = 7,
    SpaceOccupied = 8,
    Submarket = 9,
    SaleComp = 10,
    SaleCompDocument = 11,
    ShoppingCenter = 12,
    LeaseDeal = 13,
    LandForLease = 14,
    Loan = 15,
    ContactActivity = 16,
    ApartmentModel = 17,
    PropertyResidential = 18,
    ApartmentUnit = 19,
    Article = 20,
    Intermediate =21,
    Listing = 103,
    College = 23,
    Tenant = 105,
    Unknown = -1
}